#!/bin/bash

echo "Removing old data..."
find . -name "*.forThePlanetData" -exec rm -f {} \;
rm -f "output/*.csv"
find . -name "*.png" -exec rm -f {} \;

echo "Creating plots..."
Rscript ./scripts/plotsGenerator.r

echo "Done"